"""Create pcb_orders table

Revision ID: 3ffabeb178cd
Revises: 75ac59ddf551
Create Date: 2025-09-09 23:10:00.980453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffabeb178cd'
down_revision: Union[str, None] = '75ac59ddf551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcb_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'SHIPPED', 'CANCELLED', 'FAILED', name='pcb_orderstatus'), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('final_price_egp', sa.Float(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('base_material', sa.String(), nullable=False),
    sa.Column('manufacturing_parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcb_orders_order_number'), 'pcb_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_pcb_orders_stripe_payment_intent_id'), 'pcb_orders', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_pcb_orders_user_id'), 'pcb_orders', ['user_id'], unique=False)
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_orders_order_number', table_name='orders')
    op.drop_index('idx_orders_stripe_session_id', table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_index('idx_user_carts_user_id', table_name='user_carts')
    op.drop_index('idx_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_carts_user_id', 'user_carts', ['user_id'], unique=False)
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_stripe_session_id', 'orders', ['stripe_session_id'], unique=False)
    op.create_index('idx_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.drop_index(op.f('ix_pcb_orders_user_id'), table_name='pcb_orders')
    op.drop_index(op.f('ix_pcb_orders_stripe_payment_intent_id'), table_name='pcb_orders')
    op.drop_index(op.f('ix_pcb_orders_order_number'), table_name='pcb_orders')
    op.drop_table('pcb_orders')
    # ### end Alembic commands ###
